@api = http://127.0.0.1:4000
post https://mymone.azurewebsites.net/download
Content-Type: application/json

###

post https://transformar.senescyt.gob.ec/#/Account
Content-Type: application/json

{
    "opcionesDTO": null,
    "usuarioDTO": {
        "identificacion": "2100656665",
        "email": "",
        "apellidos": "",
        "name": "",
        "fechaNacimiento": "",
        "genero": "",
        "estadoCivil": "",
        "telefono": "",
        "celular": "",
        "token": "",
        "session": 0,
        "password": "MAXpower12",
        "nombreSegmento": "",
        "id": 0,
        "idInscripcionIES": 0,
        "mensaje": null,
        "postulacionMensaje": true,
        "estadoCalificacion": 0,
        "cupoActivo": true,
        "params": null,
        "tipoDocumento": null,
        "rutaCambioClave": "",
        "verificaPasaporte": false,
        "estadoCambioDocumento": null,
        "mensajeCambioIdent": null,
        "cambioDocTyC": false,
        "accionesAfirmativasTyC": false,
        "condicionadoBachiller": false
    },
    "iesDTO": {
        "id": null,
        "nombre": "",
        "codigosistema": "IESGRL",
        "financiamiento": "",
        "tipoIes": "",
        "categoria": "",
        "porcentaje": 0,
        "tieneEvaluacion": 0,
        "mensajeBeca": "",
        "mensajeInicioDeClase": "",
        "estadoEvaluacion": true,
        "totalCarreras": 0,
        "totalCarrerasDisponibles": 0,
        "estadoConvocatoria": true
    },
    "navegador": "Chrome",
    "aceptacion": "",
    "nombrePeriodo": "",
    "bloqueo": "",
    "encuesta": null,
    "grupo": 0,
    "fechaMinima": "",
    "mensaje": "",
    "pinDTO": null,
    "constantesDTO": null,
    "esEscolarDTO": null,
    "parroquia": null,
    "fechaFinProceso": null
}
###

{ 
      "user": "jorge593"
}
###
GET https://181.113.227.222

###

post {{api}}/demoEdit
Content-Type: application/json

{ 
     "replace": { 
      "s": "s"
     }
}

###

GET https://srienlinea.sri.gob.ec/movil-servicios/api/v1.0/deudas/porIdentificacion/2100656665


###


post http://consultas.funcionjudicial.gob.ec/informacionjudicialindividual/api/defensorPenal/buscarPorNombreCedula/2100656665/1/10/cedula


{"parametro":2100656665,"paginaIncial":1,"paginaFinal":10,"origen":"cedula"}
###

post https://www.senescyt.gob.ec/consulta-titulos-web/faces/vista/consulta/consulta.xhtml


###

post {{api}}/fixedDebst

Content-Type: application/json

{ 
     "name": "mom",
      "week":  6,
      "paid": 0,
      "total": 120,
      "action": "add",
      "user": "jorge593",
}

###
post https://mymone.azurewebsites.net/telegramBotSender

###
post https://mymone.azurewebsites.net/event
Content-Type: application/json


{ "data": { 
 "name": "Danna",
     "id": "812D301313" 
}
    
}

###
post {{api}}/overCost
Content-Type: application/json


{ "user": "jorge593",
 "value": 22.2
}



###
###
post {{api}}/telegramCV
Content-Type: application/json


{ "text": "ola xd "
}



###

post https://mymone.azurewebsites.net/editDebst
Content-Type: application/json


{ 
     "name": "ortodoncia",
     "value": 30,
      "user": "jorge593", 
      "action": "edit"
}

###
post https://mymone.azurewebsites.net/fixedDebst
Content-Type: application/json


{ 
     "name": "tv",
      "week":  4,
      "paid": 0,
      "total": 30 ,
      "action": "edit",
      "mount": 30,
      "user": "jorge593"
}
###

post https://mymone.azurewebsites.net/money
Content-Type: application/json


{ "data": { 
       "name": "jorge593"
}
   
     
}

###

post https://mymone.azurewebsites.net/newContabilitie

Content-Type: application/json


{ 
      "name": "jorge593",
      "date": { 
            "day": "Sun"
      }
}
###

post https://mymone.azurewebsites.net/overCost
Content-Type: application/json


{ 
      "user": "jorge593",
      "date": { 
            "day": "Sun"
      }
}


###
###

post https://mymone.azurewebsites.net/overCost
Content-Type: application/json


{ 
      "name": "jorge593",
      "date": { 
            "day": "Sun"
      }
}


###
post https://app.tuenti.ec/ms-tuenti-gateway/tuenti/request
Content-Type: application/json


{ 
      "number": <962716235,
      "data": "6bb5ffb2777f3b031c9978a4bbe91561a4d5480697e448eb7be98f20e7cb7e37bed5cc4db41c240f8517b146c8ea7e4a5565a75d70227838dc6df93b6b95e296406634cccb125e5f527d196c4f49b1ab10608f4cef6c26bf42900be1eb9eb85a8f5b81da8ddbfff105dbd583e4d7cd25d342009c8f37a3516fd1b396de9881c48b910e12c15c559e1deee72f93d00b431c2fe2cee4afd5a917e081bcbef13bf4a010906b8462bdce400727ccd011ba817546aee3b39fe0cd15cb299e67fbf2ea59d6402b44994113847e95016d9b7d6a31c729a5bca8d3a631413597417e0148bf08551036b6be67091eb8e0f8c2b94c071d376c88709a800f9ef57c84c8c256face673b10b5d616c04a3fc8303dea5a718d8b39497f2127bb2c039baad067493f3dd27b4e477c29ac630406f3f3caac677884810b10d921ed7037447aa2936e71cce12629f51af9ce8eb60408ed723cd7871736dabd1a71c4c4424d8e71d947aed25cd9e944114a8146641822b088e99f0efa2675f06819328a7f5df568c2373f3dd27b4e477c29ac630406f3f3caacc8ed2b398d378fc4c9d5d15cec5a977c"
}

###
//post https://mymone.azurewebsites.net/udapteDebts
post {{api}}/udapteDebts
Content-Type: application/json



     { 
      "name": "jorge593",
        "val": 0.01,
        "from": "patrimonio",
        "to": "luis",
        "action": "de"
      }




###

get https://mymone.azurewebsites.net/eventt

###

get {{api}}/eventt

###

post https://textbelt.com/text 
Content-Type: application/json


{ 
     
       "phone": "+593959434867",
    "message": "ola",
    "key": "c40aecb8bc1497d84c1c1c28071cd860adeb22c2mo8U8P7eDS33otmOGpQg1FR0e"
     
     
    
}

##
post {{api}}/edit
Content-Type: application/json


{ 
      "edit": { 
            "nameEdit": "cooperativa", 
            "valueEdit": 5, 
            "typeCost": "fixed",
            "name": "jorge593"
      } 

}

###



get https://media.geeksforgeeks.org/wp-content/uploads/20200924102121/Screenshot58.png
