@api = http://127.0.0.1:4000
post {{api}}/money
Content-Type: application/json


###


post {{api}}/event
Content-Type: application/json



     { 
      "data": "812"
      }




###

post {{api}}/edit
Content-Type: application/json


{ 
      "edit": { 
            "nameEdit": "cooperativa", 
            "valueEdit": 5, 
            "typeCost": "fixed",
            "name": "jorge593"
      } 

}
